<!DOCTYPE html>

<html lang="ru" prefix="og: http://ogp.me/ns#">

<head>
    <base href=""/>
    <title>Triangle Web</title>
    <meta charset="utf-8"/>

    <!-- About App -->
    <meta name="language" content="RU"/>
    <meta name="robots" content="noindex,nofollow"/>

    <!-- About System -->
    <meta name="generator" content="Triangle Framework"/>
    <meta name="server" content="Localzet Server <?= localzet\Server::getVersion() ?? '' ?>"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <!-- SEO -->
    <link rel="shortcut icon" type="image/svg+xml" href="//cdn.localzet.com/public/media/localzet.svg"/>

    <meta name="color-scheme" content="dark light">
    <meta name="theme-color" media="(prefers-color-scheme: dark)" content="#12121200">
    <meta name="theme-color" media="(prefers-color-scheme: light)" content="#ffffff00">

    <!-- Fonts -->
    <link rel="stylesheet" type="text/css"
          href="https://fonts.googleapis.com/css?family=Nunito:100,200,300,400,500,600,700,800,900"/>

    <style>
        body {
            background-color: #000;
            font-family: Nunito, monospace;
            font-weight: 600;
            text-align: center;
            text-decoration: none !important;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
            overflow: hidden;
        }

        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            text-align: center;
            margin-bottom: 5px;
        }

        .footer a {
            text-decoration: none;
            color: #6e7681;
            margin: 0 3px;
            /* white-space: nowrap; */
            display: inline-block;
        }

        .footer a b {
            color: #50cd89;
        }

        img {
            display: block;
            -webkit-user-select: none;
            transition: background-color 300ms;
            max-width: 800px;
            width: 800px;
        }

        hr {
            border-color: #50cd89;
            border-radius: 50%;
            width: 100%;
        }

        @media (max-width: 900px) {
            img {
                margin: auto 5%;
                width: 90%;
                height: auto;
            }
        }
    </style>
</head>

<body>
<br/>
<center>
    <h1>
        Hello <?= htmlspecialchars($name) ?>!
    </h1>
</center>
<div class="footer">
    <hr>
    <a href="https://github.com/localzet/server">Powered by <b>Localzet
            Server <?= @localzet\Server::getVersion() ?? '' ?></b></a>
</div>
</body>

</html>